openapi: 3.0.3
info:
  title: PetSitter API
  version: "0.1"
servers:
- url: /
tags:
- name: Users
  description: User-related operations
- name: Jobs
  description: Job-related operations
paths:
  /users:
    post:
      tags:
      - Users
      summary: Register User
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "201":
          description: Created
          headers:
            Location:
              style: simple
              explode: false
              schema:
                type: string
      x-swagger-router-controller: Users
  /users/{id}:
    get:
      tags:
      - Users
      summary: View User
      operationId: viewUserWithId
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      x-swagger-router-controller: Users
    put:
      tags:
      - Users
      summary: Modify User
      operationId: modifyUserWithId
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      x-swagger-router-controller: Users
    delete:
      tags:
      - Users
      summary: Delete User
      operationId: deleteUserWithId
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "204":
          description: Ne Content
      x-swagger-router-controller: Users
  /jobs:
    get:
      tags:
      - Jobs
      summary: List All Jobs
      operationId: listAllJobs
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
              examples:
                with-some-data:
                  summary: With some data
                  value:
                    items:
                    - id: 123
                      creator_user_id: 345
                      start_time: 2020-06-01T00:00:00Z
                      end_time: 2020-06-02T00:00:00Z
                      dog:
                        name: Fido
                        age: 3
                        breed: Doberman
                        size: medium
                      activity: walk
                    - id: 234
                      creator_user_id: 345
                      start_time: 2020-06-01T00:00:00Z
                      end_time: 2020-06-02T00:00:00Z
                      dog:
                        name: Rex
                        age: 2
                        breed: Rottweiler
                        size: large
                      activity: sit
                    - id: 234
                      creator_user_id: 345
                      start_time: 2020-06-01T00:00:00Z
                      end_time: 2020-06-02T00:00:00Z
                      dog:
                        name: Blossom
                        age: 2
                        breed: Rottweiler
                        size: large
                      activity: walk
      x-swagger-router-controller: Jobs
    post:
      tags:
      - Jobs
      summary: Create Job
      operationId: createJob
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Job'
      responses:
        "201":
          description: Created
          headers:
            Location:
              style: simple
              explode: false
              schema:
                type: string
      x-swagger-router-controller: Jobs
  /jobs/{id}:
    get:
      tags:
      - Jobs
      summary: View Job
      operationId: viewJobWithId
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
      x-swagger-router-controller: Jobs
    put:
      tags:
      - Jobs
      summary: Modify Job
      operationId: modifyJobWithId
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Job'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
      x-swagger-router-controller: Jobs
    delete:
      tags:
      - Jobs
      summary: Delete job
      operationId: deleteJobWithId
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "204":
          description: No Content
      x-swagger-router-controller: Jobs
  /jobs/{id}/job-applications:
    get:
      tags:
      - Jobs
      summary: List Applications For Job
      operationId: viewApplicationsForJob
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
      x-swagger-router-controller: Jobs
    post:
      tags:
      - Jobs
      summary: Create Job Application
      operationId: createJobApplication
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobApplication'
      responses:
        "201":
          description: Created
          headers:
            Location:
              style: simple
              explode: false
              schema:
                type: string
      x-swagger-router-controller: Jobs
  /users/{id}/jobs:
    get:
      tags:
      - Users
      summary: List Jobs For User
      operationId: listJobsForUser
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
      x-swagger-router-controller: Users
  /users/{id}/job-applications:
    get:
      tags:
      - Users
      summary: List Applications For User
      operationId: viewApplicationsForUser
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
              examples:
                empty:
                  summary: Zero Job Applications
                  value:
                    items: []
                two-items:
                  summary: Two Job Applications
                  value:
                    items:
                    - id: 123
                      user_id: 123
                      job_id: 123
                      status: PENDING
                    - id: 123
                      user_id: 123
                      job_id: 123
                      status: COMPLETE
                many:
                  summary: Many Job Applications
                  value:
                    items:
                    - id: 0
                      user_id: 358
                      job_id: 4012
                      status: COMPLETE
                    - id: 1
                      user_id: 3089
                      job_id: 3902
                      status: PENDING
                    - id: 2
                      user_id: 4040
                      job_id: 5269
                      status: PENDING
                    - id: 3
                      user_id: 5636
                      job_id: 8420
                      status: PENDING
                    - id: 4
                      user_id: 9540
                      job_id: 9505
                      status: COMPLETE
                    - id: 5
                      user_id: 9873
                      job_id: 3215
                      status: PENDING
                    - id: 6
                      user_id: 6032
                      job_id: 7365
                      status: COMPLETE
                    - id: 7
                      user_id: 5999
                      job_id: 1159
                      status: COMPLETE
                    - id: 8
                      user_id: 2897
                      job_id: 7982
                      status: COMPLETE
                    - id: 9
                      user_id: 227
                      job_id: 9245
                      status: CANCELLED
                    - id: 10
                      user_id: 741
                      job_id: 2752
                      status: CANCELLED
                    - id: 11
                      user_id: 9059
                      job_id: 338
                      status: PENDING
                    - id: 12
                      user_id: 1379
                      job_id: 4531
                      status: COMPLETE
                    - id: 13
                      user_id: 2031
                      job_id: 9375
                      status: COMPLETE
                    - id: 14
                      user_id: 3643
                      job_id: 5175
                      status: CANCELLED
                    - id: 15
                      user_id: 5470
                      job_id: 831
                      status: CANCELLED
                    - id: 16
                      user_id: 3265
                      job_id: 5597
                      status: PENDING
                    - id: 17
                      user_id: 2815
                      job_id: 7719
                      status: PENDING
                    - id: 18
                      user_id: 8306
                      job_id: 679
                      status: PENDING
                    - id: 19
                      user_id: 9742
                      job_id: 8239
                      status: PENDING
                    - id: 20
                      user_id: 4851
                      job_id: 940
                      status: PENDING
                    - id: 21
                      user_id: 6700
                      job_id: 4040
                      status: PENDING
                    - id: 22
                      user_id: 7067
                      job_id: 6016
                      status: PENDING
                    - id: 23
                      user_id: 3265
                      job_id: 1822
                      status: PENDING
                    - id: 24
                      user_id: 8333
                      job_id: 9988
                      status: PENDING
                    - id: 25
                      user_id: 7543
                      job_id: 9307
                      status: PENDING
                    - id: 26
                      user_id: 5429
                      job_id: 7511
                      status: COMPLETE
                    - id: 27
                      user_id: 3576
                      job_id: 1710
                      status: PENDING
                    - id: 28
                      user_id: 590
                      job_id: 2634
                      status: COMPLETE
                    - id: 29
                      user_id: 2327
                      job_id: 7205
                      status: CANCELLED
                    - id: 30
                      user_id: 2193
                      job_id: 7421
                      status: COMPLETE
                    - id: 31
                      user_id: 5014
                      job_id: 6781
                      status: CANCELLED
                    - id: 32
                      user_id: 9216
                      job_id: 8047
                      status: COMPLETE
                    - id: 33
                      user_id: 3369
                      job_id: 7438
                      status: CANCELLED
                    - id: 34
                      user_id: 9825
                      job_id: 6758
                      status: PENDING
                    - id: 35
                      user_id: 3250
                      job_id: 7760
                      status: COMPLETE
                    - id: 36
                      user_id: 1552
                      job_id: 4030
                      status: COMPLETE
                    - id: 37
                      user_id: 9221
                      job_id: 3971
                      status: CANCELLED
                    - id: 38
                      user_id: 6816
                      job_id: 7878
                      status: PENDING
                    - id: 39
                      user_id: 6109
                      job_id: 4060
                      status: CANCELLED
      x-swagger-router-controller: Users
  /job-applications/{id}:
    put:
      tags:
      - Jobs
      summary: Modify Job Application
      operationId: modifyJobApplicationWithId
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        description: Update the application details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobApplication'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobApplication'
      x-swagger-router-controller: Jobs
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        password:
          type: string
        full_name:
          type: string
        roles:
          type: array
          items:
            type: string
      example:
        password: password
        full_name: full_name
        roles:
        - roles
        - roles
        id: 0
        email: email
    Job:
      type: object
      properties:
        id:
          type: integer
        creator_user_id:
          type: integer
        start_time:
          type: string
        end_time:
          type: string
        activity:
          type: string
        dog:
          $ref: '#/components/schemas/Dog'
      example:
        creator_user_id: 6
        start_time: start_time
        activity: activity
        end_time: end_time
        id: 0
        dog:
          size: size
          name: name
          age: 1
          breed: breed
    Dog:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
        breed:
          type: string
        size:
          type: string
      example:
        size: size
        name: name
        age: 1
        breed: breed
    JobApplication:
      type: object
      properties:
        id:
          type: integer
        status:
          type: string
        user_id:
          type: integer
        job_id:
          type: integer
      example:
        user_id: 6
        job_id: 1
        id: 0
        status: status
    inline_response_200:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Job'
      example:
        items:
        - creator_user_id: 6
          start_time: start_time
          activity: activity
          end_time: end_time
          id: 0
          dog:
            size: size
            name: name
            age: 1
            breed: breed
        - creator_user_id: 6
          start_time: start_time
          activity: activity
          end_time: end_time
          id: 0
          dog:
            size: size
            name: name
            age: 1
            breed: breed
    inline_response_200_1:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/JobApplication'
      example:
        items:
        - user_id: 6
          job_id: 1
          id: 0
          status: status
        - user_id: 6
          job_id: 1
          id: 0
          status: status
